### ISSUE TITLE
Select scheme to test

### ISSUE THREAD

**Issue by mtitolo** [supermarin/xclisten#1]
The app I'm currently working on has 2 schemes, each with a corresponding test suite. Xclisten expects to use the scheme with the same name as the workspace, when the tests should be run from the other scheme.

It'd be great to have a `-scheme` flag so we can select which test suite to run.

**Comment by supermarin** [comment]
:+1: on it

**Comment by yas375** [comment]
:+1:

**Comment by supermarin** [comment]
@mtitolo @yas375 Fixed in https://github.com/mneorr/xclisten/commit/77eee9454b5dce6d4f6a67a6db5f83c8c6055e4b

You can also specify a device you want to run on:

``` bash
$ xclisten -d iphone5s  # default
$ xclisten -d iphone4
$ xclisten -d iphone5
```

**Comment by yas375** [comment]
@mneorr thank you! :)
