### ISSUE TITLE
Listening to the wrong workspace

### ISSUE THREAD

**Issue by NachoSoto** [supermarin/xclisten#12]
First of all, great job with this! :)

I'm having this problem and I'm not sure what's wrong:
I'm running this command:

``` bash
xclisten --ios -w myproject.xcworkspace
```

And this is what I see:

``` bash
Started xclistening to Dependencies/.../.../somedependency.xcworkspace
```

For some reason it's ignoring the `--workspace` parameter and listening to some other one. If I ignore the `-w` parameter I get the same result.

Please let me know what other information I can provide :)

**Comment by supermarin** [comment]
It'd be awesome if you could provide output of `tree -d` from the base dir you're running `xclisten`

**Comment by supermarin** [comment]
You might need to `brew install tree`

**Comment by NachoSoto** [comment]
Unfortunately I can't because it's my work project :/

**Comment by supermarin** [comment]
gotcha. i might see what's the problem - it picks up the first found project alphabetically instead of recursion level

**Comment by supermarin** [comment]
So that's one problem - let me take a look on the second one :)

**Comment by NachoSoto** [comment]
That makes sense :) The dependency starts with `C` and the root projects starts with `G`.

**Comment by supermarin** [comment]
Solved and :shipit: , update to 0.0.5

**Comment by NachoSoto** [comment]
Awesome thanks!

**Comment by supermarin** [comment]
btw, you should be able to run just `xclisten` without any flags
