### ISSUE TITLE
Add iPads support to the list of devices

### ISSUE THREAD

**Issue by orta** [supermarin/xclisten#13]
Is it just for documentation that it only lists 

`-d, --device                     Simulated device [iphone5s, iphone5, iphone4]. Default is iphone5s`

or is there a technical reason for this?

/cc @dblock

**Comment by supermarin** [comment]
@orta it's only my laziness / hacking on sunday.
I'll add them today

**Comment by supermarin** [comment]
@orta here you go sir https://github.com/mneorr/xclisten/commit/2501e7de5d4f9060bc08889d65a37594f7af0ea7

**Comment by orta** [comment]
Woo Hoo he's the marin.
